### PR TITLE
Maven support

### PR DESCRIPTION
**Pull request by kmagiera**
This diff add maven build system for UrlImageViewHelper library. Issue #28

1) I've decided not to create parent pom for sample and library since it is not recommended by maven central.
2) This diff may cause some problems under eclipse without m2e and m2e-android. To fix that problem I would recommend to remove .settings and .project (and all other eclipse specific stuff) from version controll. Otherwise you may want to create separate branch where maven support will be maintained.
3) Finally, I had to remove references to junit.framework.Assert since junit libraries should only be used in test scope.

### CODE REVIEW

**Comment by kmagiera** [comment]
This addresses issue #28

**Comment by koush** [comment]
Thanks.

Not very familiar with maven; why are the changes necessary in .project and .settings?

**Comment by kmagiera** [comment]
Changes in .classpath creates link between maven dependencies and eclipse dependencies, those are necessery for eclipse for build/autocompletion of libraries declared as dependency in maven.
Changes in .project says to eclipse that is should monitor pom.xml for changes (new dependencies can araise, etc.). Also maven specific context menu is available within eclipse.

I checked those changes under eclipse indigo w/o m2eclipse plugin and it builds normally. You can also refer to this lib: https://github.com/ChristopheVersieux/HoloEverywhere/tree/master/library, which also builds normally under eclipse w/o maven support.

**Comment by koush** [comment]
In this case, couldn't a separate maven directory be created in this project structure, with it's own .project and .classpath that refers to the sources in the UrlImageViewHelper directory?

That may be the way to go. I'd rather not consumers of this library git pull an update and suddenly everything breaks due to breaking changes in the aforementioned files.

**Comment by kmagiera** [comment]
i've tested this under two modern installations of eclipse without any maven plugins and it didn't case any problems.

but if it doesn't covince you we can skip .project and .classpath changes. Maven users will still be able to build it in console, but most of them won't even need to build the project after we put it to maven central. Just let me know so I can prepare update for this diff.

**Comment by koush** [comment]
Let me try on my end.

**Comment by koush** [comment]
Apparently I do have maven installed (don't recall ever installing or using it). The project now fails to build/load:

Description Resource    Path    Location    Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:2.4.3:resources (execution: default-resources, phase: process-resources)   pom.xml /UrlImageViewHelper line 3  Maven Project Build Lifecycle Mapping Problem

**Comment by kmagiera** [comment]
Ok. So I've decided to revert changes in .project and .classpath.

After you merge this diff I will send version 1.0 to maven central and get back to you with doc update for maven users.

**Comment by koush** [comment]
Thanks, released using sonatype's hosting

**Pull request closed without merging**
