### PR TITLE
just cleaner Java code

### PR DESCRIPTION
**Pull request by pedronveloso**
removed some unnecessary semicolons and variables

### CODE REVIEW

**Comment by koush** [comment]
Hi @pedronveloso! Thanks for this.

I see this is the fix for the exception you ran into in https://github.com/koush/UrlImageViewHelper/issues/13

As I mentioned in that thread, the urls that were passed in are invalid (due to spaces in the path, which were not escaped). I'm hesitant to try to do any "browser style" url cleaning, as I prefer the failure behavior in the case that bad input is provided. I'd prefer not to try to enable bad practices :)

Though, to be honest, I'm a little surprised that URL and Uri don't choke on the url string, and also don't properly escape it. This may be a bug in Android's url parsing classes. Will need to compare to a desktop Java runtime.

**Comment by pedronveloso** [comment]
@koush yeah it's strange that the native components don't take care of that at some level, but then again this kind of situations (something left out, incomplete) it's not breaking-news in Android

You can deny the "fix URLs", but the "cleaner code  85dff3d" is still valid. I'll be glad to clean it up a bit more in the future, but I guess right now it doesn't matter that much because of this being a WIP. BTW, will you be going forward with the NIO branch, or perhaps integrate it with AndroidAsync repo?

**Comment by koush** [comment]
@pedronveloso Oh, I didn't realize there were two commits. Uh.... github doesn't give me an easy way to just take one and not both commits. I'll grab that one later.

I am going to have UrlImageViewHelper optionally use NIO if the AndroidAsync library is available. Here's sample code to do that right now:

https://gist.github.com/3447438

It switches the Image downloader to use NIO.

I've already deleted the nio branch in this project; that was just for testing. I'll be updating AndroidAsync from here on out.

**Comment by pedronveloso** [comment]
@koush in that case don't worry about that pull request, it is so minor that does not worth the trouble.

Thanks for the Gist, that was exactly what I wanted :).

**Pull request closed without merging**
