### PR TITLE
Disable disk cache for Content Scheme Url 

### PR DESCRIPTION
**Pull request by EaseTheWorld**
Disable disk cache for Content Scheme Url 
(except ContactsContract.Contacts.CONTENT_URI)

if url starts with content scheme, set filename and file to null then
mDefaultDownloader.download() -> just call loader.run() -> loadDrawableFromUrl()

### CODE REVIEW

**Comment by EaseTheWorld** [comment]
I modified a little for cleaner code.

**Comment by koush** [comment]
I agree that this is needed. But I'm hesitant to accept this change:
I need to refactor URI handling and loading altogether. It's quite messy (and I recently added file URI support). And moving the stuff out into discrete classes with more explicit handling of the streams and caching would make sense.

I'll work on that now, and we can consolidate our changes.

**Comment by EaseTheWorld** [comment]
Ok. I'll be waiting :+1:

**Comment by koush** [comment]
Hi, take a look at this please:

https://github.com/koush/UrlImageViewHelper/commit/7346758524b2ecc0c68fcbd9646e4076f249e607

I've refactored the downloaders into their own classes which can then tell the loader whether or not to cache the image in the file system.

Note that the file will still be written. The only difference now is that it will delete the file after it is completed loading. The file is still written because it needs to be read twice: once to figure out the dimensions of the image, and again to actually load it. Can't do that with arbitrary streams (at least not reliably). Not all streams support mark/reset.

**Comment by EaseTheWorld** [comment]
Well... the reason I started this thread is to avoid writing cache file.
Imagine the worst case. You couldn't read the local file because disk is
full...?

What I suggest is...
- Move the onDownloadComplete to each UrlDownloader.doInBackground
  and it passes bitmap to onPostExecute->completion.(to do so, completion
  should be more than Runnable)
  So each UrlDownloader can handle stream or file by its own.
  For example, HttpUrlDownloader will download from remote, save to file
  and read from the file.
  ContentUrlDownloader will read from file directly.
- Choose UrlDownloader at first and use its allowCache(or maybe
  getFilenameForUrl) to decide checking cache or not.
- If file cache hit, we could also use FileUrlDownloader in that case.

2013/1/15 Koushik Dutta notifications@github.com

**Comment by koush** [comment]
Do you mind checking if mark/reset works on content streams? I suspect it might (vs a http stream, which obviously cant be mark/reset). If so, that may be the solution to use to prevent caching.

I'm in agreement that caching the file is not ideal. Unfortunately, there's no decent way to check the dimensions f the file without caching it first.
Well, I suppose the other option is a inputstream wrapper that buffers the content stream's data that was read, so a reopen is not necessary. That should actually not be too hard to implement.

**Comment by koush** [comment]
Yeah, this should work pretty well:

http://developer.android.com/reference/java/io/BufferedInputStream.html

A BufferedInputStream adds functionality to another input stream-namely, the ability to buffer the input and to support the mark and reset methods.

**Comment by EaseTheWorld** [comment]
AFAIK, BufferedInputStream only keeps specific amount of data (readLimit).

content url stream is FileInputStream so it doesn't support mark/reset but
we can get FD from it so BitmapFactory.decodeFileDescriptor() can be used
without opening twice.

2013/1/16 Koushik Dutta notifications@github.com

**Pull request closed without merging**
