### PR TITLE
Add support for "file:///android_asset/" URIs

### PR DESCRIPTION
**Pull request by tadfisher**
Why not?

### CODE REVIEW

**Comment by koush** [comment]
Can you use asset:// instead? That would make more sense.

**Comment by koush** [comment]
Err. Just googled this. I cant tell if file://android_asset is an official android recognized uri. Why do you need this? Trying to figure out what else uses this.

**Comment by koush** [comment]
Found it:

https://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccess(boolean)

Weird. Learn something new every day.

**Comment by tadfisher** [comment]
Haha, yeah. WebView only accepts that format. I don't believe I've ever come across an `asset:///` uri in the wild.

**Pull request merged**
